import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'notes.freezed.dart';
part 'notes.g.dart';

@freezed
abstract class Note with _$Note {
  factory Note({
    @JsonKey(name: 'Content') @Default('') String Content,
    @JsonKey(name: 'Kind') @Default('') String Kind,
  }) = _Note;

  factory Note.fromJson(Map<String, dynamic> json) => _$NoteFromJson(json);
}
