# Config file for Air - https://github.com/cosmtrek/air

root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main cmd/server/main.go"
  bin = "./tmp/main"
  include_ext = ["go", "html"]
  exclude_dir = ["assets", "tmp", "vendor", "frontend", "build"]
  log = "air_errors.log"

[log]
  time = true

[misc]
  delve = false
